language:
  ruby

sudo: required

before_script:
  - echo testes
  - uname -a 
  - curl ipecho.net/plain; echo
  - gcloud alpha organizations list
  - sudo gcloud compute project-info describe
  - sudo gcloud compute instances list
  - sudo gcloud compute networks subnets list
  - sudo gcloud compute routes list
  - sudo gcloud compute networks create testnetwork3 --mode auto
  - sudo gcloud instances create sbtestinstance --subnet testnetwork3
  - sudo gcloud compute networks subnets list
  - sudo gcloud compute instances list



  

rvm:
  - 2.2.2
